### ISSUE TITLE
I am sorry, I did not understand that.

### ISSUE THREAD

**Issue by emsi** [githubnext/githubnext#6]
`I am sorry, I did not understand that.` is the only answer I ever get for any command despite the perfect transcription in the chat window.

For example:
![image](https://user-images.githubusercontent.com/433383/227353565-94dff02c-7b37-4af6-a4c5-62ae53cdcce2.png)

**Comment by emsi** [comment]
Is it fixed?

**Comment by rahulpandita** [comment]
@emsi yes the original issue had been fixed was not able to get around to closing this.
